In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree

In [2]:
df=pd.read_csv('book1.csv')

In [3]:
df=df.dropna(subset=['tp_classificacao_final'])

In [4]:
df=df.drop(['nu_idade','tp_sexo','tp_raca_cor'],axis=1)

In [5]:
df=df.drop(df[df['tp_classificacao_final'] == 1].index)
df=df.drop(df[df['tp_classificacao_final'] == 2].index)
df=df.drop(df[df['tp_classificacao_final'] == 8].index)
df=df.drop(df[df['tp_classificacao_final'] == 11].index)
df=df.drop(df[df['tp_classificacao_final'] == 12].index)
#df=df.drop(df[df['tp_classificacao_final'] == 13].index)

In [6]:
df3=df.fillna({'tp_gestante':df['tp_gestante'].mode()[0],'tp_zona_residencia':df['tp_zona_residencia'].mode()[0],
               'febre':df['febre'].mode()[0],'mialgia':df['mialgia'].mode()[0],
               'cefaleia':df['cefaleia'].mode()[0],'exantema':df['exantema'].mode()[0],'vomito':df['vomito'].mode()[0],
               'nausea':df['nausea'].mode()[0],'dor_costas':df['dor_costas'].mode()[0],'conjutivite':df['conjutivite'].mode()[0],
               'artrite':df['artrite'].mode()[0],'artralgia':df['artralgia'].mode()[0],'petequia_n':df['petequia_n'].mode()[0],
               'laco':df['laco'].mode()[0],'dor_retro':df['dor_retro'].mode()[0],'diabetes':df['diabetes'].mode()[0],
               'hematolog':df['hematolog'].mode()[0],'hepatopat':df['hepatopat'].mode()[0],'renal':df['renal'].mode()[0],
               'hipertensao':df['hipertensao'].mode()[0],'acido_pept':df['acido_pept'].mode()[0],'auto_imune':df['auto_imune'].mode()[0]})

In [7]:
x=df3.iloc[:,:-1]
y=df3.iloc[:,22]

In [8]:
df3['tp_classificacao_final'].value_counts()

tp_classificacao_final
10.0    40817
5.0     21817
13.0     6848
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=.20, random_state=1)

# Decision tree classifier

In [11]:
classifier=tree.DecisionTreeClassifier()

In [12]:
classifier.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [13]:
classifier.score(xtest,ytest)

0.6521551413974239

In [14]:
cpred=classifier.predict(xtest)

In [15]:
accuracy_score(ytest,cpred)

0.6521551413974239

In [16]:
confusion_matrix(ytest,cpred)

array([[1393, 2674,  243],
       [ 687, 7198,  320],
       [ 255,  655,  472]], dtype=int64)

In [17]:
print(classification_report(ytest,cpred))

              precision    recall  f1-score   support

         5.0       0.60      0.32      0.42      4310
        10.0       0.68      0.88      0.77      8205
        13.0       0.46      0.34      0.39      1382

    accuracy                           0.65     13897
   macro avg       0.58      0.51      0.53     13897
weighted avg       0.63      0.65      0.62     13897



# Logistic Regression

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
Lreg=LogisticRegression()

In [20]:
Lreg.fit(xtrain,ytrain)

C:\Users\OBYDUL HAQUE EMON\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
Lreg.score(xtest,ytest)

0.6468302511333381

In [22]:
lpred=Lreg.predict(xtest)

In [23]:
accuracy_score(ytest,lpred)

0.6468302511333381

In [24]:
confusion_matrix(ytest,lpred)

array([[1118, 2894,  298],
       [ 436, 7343,  426],
       [ 139,  715,  528]], dtype=int64)

In [25]:
print(classification_report(ytest,lpred))

              precision    recall  f1-score   support

         5.0       0.66      0.26      0.37      4310
        10.0       0.67      0.89      0.77      8205
        13.0       0.42      0.38      0.40      1382

    accuracy                           0.65     13897
   macro avg       0.58      0.51      0.51     13897
weighted avg       0.64      0.65      0.61     13897



# Random Forrest Classifier

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
Rforest=RandomForestClassifier()

In [28]:
Rforest.fit(xtrain,ytrain)

RandomForestClassifier()

In [29]:
Rforest.score(xtest,ytest)

0.6530186371159243

In [30]:
rpred=Rforest.predict(xtest)

In [31]:
accuracy_score(ytest,rpred)

0.6530186371159243

In [32]:
confusion_matrix(ytest,rpred)

array([[1360, 2679,  271],
       [ 642, 7194,  369],
       [ 232,  629,  521]], dtype=int64)

In [33]:
print(classification_report(ytest,rpred))

              precision    recall  f1-score   support

         5.0       0.61      0.32      0.42      4310
        10.0       0.69      0.88      0.77      8205
        13.0       0.45      0.38      0.41      1382

    accuracy                           0.65     13897
   macro avg       0.58      0.52      0.53     13897
weighted avg       0.64      0.65      0.62     13897



# Naiv Vaiyes

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
gnb=GaussianNB()

In [36]:
gnb.fit(xtrain,ytrain)

GaussianNB()

In [37]:
gpred=gnb.predict(xtest)

In [38]:
accuracy_score(ytest,gpred)

0.6202057998129092

In [39]:
from sklearn.naive_bayes import BernoulliNB

In [40]:
bnb=BernoulliNB()

In [41]:
bnb.fit(xtrain,ytrain)

BernoulliNB()

In [42]:
bpred=bnb.predict(xtest)

In [43]:
accuracy_score(ytest,bpred)

0.5904151975246456

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
mnb=MultinomialNB()

In [46]:
mnb.fit(xtrain,ytrain)

MultinomialNB()

In [47]:
mpred=mnb.predict(xtest)

In [48]:
accuracy_score(ytest,mpred)

0.594876592070231

# KNN

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
knn=KNeighborsClassifier(n_neighbors=223)

In [51]:
knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=223)

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
sc_x=StandardScaler()
a=sc_x.fit_transform(xtrain)
b=sc_x.transform(xtest)

In [54]:
knn.fit(a,ytrain)

KNeighborsClassifier(n_neighbors=223)

In [55]:
kpred=knn.predict(b)

In [56]:
accuracy_score(ytest,kpred)

0.6547456285529251

In [57]:
confusion_matrix(ytest,kpred)

array([[1382, 2686,  242],
       [ 655, 7231,  319],
       [ 255,  641,  486]], dtype=int64)

In [58]:
print(classification_report(ytest,kpred))

              precision    recall  f1-score   support

         5.0       0.60      0.32      0.42      4310
        10.0       0.68      0.88      0.77      8205
        13.0       0.46      0.35      0.40      1382

    accuracy                           0.65     13897
   macro avg       0.58      0.52      0.53     13897
weighted avg       0.64      0.65      0.62     13897



# SVM

In [59]:
from sklearn.svm import SVC

In [60]:
Svm=SVC(gamma='auto')

In [61]:
Svm.fit(xtrain,ytrain)

SVC(gamma='auto')

In [ ]:
spred=Svm.predict(xtest)

In [ ]:
accuracy_score(ytest,spred)

In [ ]:
confusion_matrix(ytest,spred)

In [ ]:
print(classification_report(ytest,spred))